### ISSUE TITLE
🔷 [Epic] Lockup Creation

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#140]
This epic is part of the [NEAR Treasury](https://github.com/NEAR-DevHub/.github/issues/12) product development initiative.

# Background
This epic focuses on enabling the creation and management of lockup accounts, including making payments and transfers from these accounts.

# Epic Level Stories
- [x] As a Treasury Management user, I want to view detailed information about lockup accounts so that I can make informed decisions about our team's assets.
- [x] As a Treasury Management user, I want to have the ability to make Stake Delegation requests from lockup account
- [x] As a Treasury Management user, I want to have the ability to make payment requests from lockup account
- [x] As a Treasury Management user, I want to have the ability to create and manage lockup accounts
- [ ] As a Treasury Management user, I want to have the ability to make asset transfers from lockup account
