### ISSUE TITLE
Track configuration of the SputnikDAO contract to support the treasury workflow

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-treasury-dashboard#15]
This issue is to track/discuss changes that need to be made in order to support the treasury dashboard.

Research issue NEAR-DevHub/neardevhub-bos#622 is a relevent source for more information.

Our goal is to deploy a DAO on the `treasury.devhub.near` account with the right policy configuration.

The [sputnik dao repo](https://github.com/near-daos/sputnik-dao-contract) contains a dao factory to deploy daos as subaccounts.
`devhub.near` however will not contain a factory but the smart contract to support devhub posts/moderators/communities etc..

We won't need a factory contract to manage multiple DAO's so we can just deploy a single DAO instance on the `treasury.devhub.near` account. On initialisation we can set the right policy of the DAO, but this can also be changed later on by submitting proposals of kind `ChangePolicy`. 

In order to be able to edit the policy later on (editing trustees and moderators) there also needs to be a council role. Below I wrapped the policy config in the parameters of the `ChangePolicy` proposal to show case how that would work.

<details><summary>Change Policy parameters</summary>

```json
{
  "proposal": {
    "kind": {
      "ChangePolicy": {
        "policy": {
          "roles": [{
              "name": "council",
              "kind": {
                "Group": [
                  "devhub.near"
                ]
              },
              "permissions": [
                "*:Finalize",
                "*:AddProposal",
                "*:VoteApprove",
                "*:VoteReject",
                "*:VoteRemove"
              ],
              "vote_policy": {
                "Group": {
                  "weight_kind": "RoleWeight",
                  "quorum": "0",
                  "threshold": 1
                }
              }
            },
            {
              "name": "trustees",
              "kind": {
                "Group": [
                  "thomasguntenaar.testnet",
                  "efiz.testnet",
                  "megha2001.testnet"
                ]
              },
              "permissions": [
                "call:Finalize",
                "call:VoteApprove",
                "call:VoteReject",
                "call:VoteRemove"
              ],
              "vote_policy": {
                "Group": {
                  "weight_kind": "RoleWeight",
                  "quorum": "0",
                  "threshold": 1
                }
              }
            },
            {
              "name": "moderators",
              "kind": {
                "Group": [
                  "thomasguntenaar.testnet",
                  "efiz.testnet",
                  "megha2001.testnet"
                ]
              },
              "permissions": [
                "call:AddProposal",
                "call:RemoveProposal"
              ],
              "vote_policy": {
                "Group": {
                  "weight_kind": "RoleWeight",
                  "quorum": "0",
                  "threshold": 1
                }
              }
            }
          ],
          "default_vote_policy": {
            "weight_kind": "RoleWeight",
            "quorum": "0",
            "threshold": 1
          },
          "proposal_bond": "1000000000000000000000000",
          "proposal_period": "604800000000000",
          "bounty_bond": "1000000000000000000000000",
          "bounty_forgiveness_period": "86400000000000"
        }
      }
    },
    "description": "This is a proposal to edit the permissions of the trustees and moderators role "
  }
}
```
</details>

### Acceptance Criteria

 - [x] Determine the feasibility and effort to use SputnikDAO contract for the treasury workflow. Either via configuration or slightly modification to the SputnikDAO contract.
<details><summary>Comment</summary>
What played a guiding role in decision-making is the fact that we would prefer not to edit the DAO in order to avoid to make another audit.
</details>

 - [x] Moderator can submit a payment request, which references to a sponsorship post. The payment request amount, currency and receiver should match the sponsorship post.
<details><summary>Comment</summary>

This is possible in 2 ways:

1. A `Transfer` proposal
   1. Which takes token_id, receiver_id, amount and msg.
2. A `FunctionCall` proposal where we call `ft_transfer`
   Which takes amount and recipient_id as base64 args
  1. It can reference the sponsorship post in the proposals description.
  2. We could add another field to the proposal struct what would contain a href string. 

</details>

- [x] Moderators can manage an address book of receivers. Each receiver has a name, wallet address and two boolean property: KYC verified and test transaction sent.
<details><summary>Comment</summary>

The address book of receivers should be stored in `devhub.near` contract. This way we can manage it from there without having to change/audit the DAO contract.

</details>

- [x] The payment request receiver must be in the address book and has KYC verified, test transaction sent.
<details><summary>Comment</summary>
We could enforce this on contract level by changing the `add_proposal` function on `proposals.rs line 515`.  (and having to audit)
But this is not necessary because

1. Only moderators can add proposals
2. We can make sure that moderators would only be able to select / view recipients that are both KYC verified and have received a test tx. (rendering auditing unnecessary)

</details>

- [x] Trustees can view all payment requests sent by the moderators.
<details><summary>Comment</summary>
For now simply calling `get_propals` is sufficient. Pagination is build in, but advanced filtering is not. Indexing this will be a chore for later development.
</details>

- [x] Trustees can pay the payment request, with the amount, currency and receiver specified in the payment request, from treasury wallet account.
<details><summary>Comment</summary>
Simply vote to approve a payment request proposal.
</details>

- [x] Trustees can view all transactions (payments to payment requests)
<details><summary>Comment</summary>
I have a call on Monday with Bo about indexing.
</details>

- [x] Trustee can view the balance, staked amount and number of transactions of trustee wallet
<details><summary>Comment</summary>
Staked amount might have legal implications. Getting the balance is straightforward. Number of transactions is the same as last point.
</details>

### Policy configuration in detail

<details><summary>Roles</summary>

Permissions are strings formatted like this `[ProposalKind:Action]`. 

There are 3 roles:
1. council
4. moderators
5. trustees

Council is soly there to be able to add/remove accounts from the other roles.

Moderators can only _create_ or _remove_ payment requests by adding/removing a proposal of kind `FunctionCall` aka `call`.

```json
{
 "name": "moderators",
 "permissions": [
   "call:AddProposal",
   "call:RemoveProposal"
 ]
}
```

Trustees can only vote to approve, reject, remove or finilize proposals.

```json
{
 "name": "trustees",
 "permissions": [
   "call:Finalize",
   "call:VoteApprove",
   "call:VoteReject",
   "call:VoteRemove"
 ]
}
```

</details>

<details><summary>Default vote policy, Bonds & Bounty</summary>

`default_vote_policy` is a fallback mechanism in case the role based vote policy is configured incorrectly.
`proposal_bond` is what it the deposit cost is of a proposal. We don't need to set it high since only moderators are able to make proposals.
`proposal_period` is the time limit on proposals.
`bounty_bond` we won't use bounties.
`bounty_forgiveness_period`  won't use this either

</details>

# Time estimation

The DAO contract is good to go and won't need additional edit, so no auditing needed.

What's left todo is:
1. Find out how to deploy the DAO without a factory (1 hr)
2. Find out who will be what role. (DAO policy makers, moderator and trustee). (1 hr)
4. I would need just a few minutes to finalize the config after discussions.

The recipients address book will need:
1. A user interface to manage it.
2. The `devhub.near` will need a vector of recipient, an update function and a get_valid_recipients for the create payment request form. (1/2 day)

The indexer:
- [ ] We will need to index the transaction history and the payment request in order to have the timestamp field and the tx hash. In order to get familiar with indexer and implement it. I estimate it at 1 week so in a separate ticket.

```[tasklist]
### Tasks
```

**Comment by Tguntenaar** [comment]
Moving it back again to work on the indexer of the proposals
