### ISSUE TITLE
🔷 Epic: Sort/Search/Filter for Payments, Stake Delegation, and Settings

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#156]
This epic is part of the [NEAR Treasury](https://github.com/NEAR-DevHub/.github/issues/12) product development initiative.

# Background
Currently, there is no way for admins to search for specific requests or even open or copy links to past transactions. As the number of requests will grow over time, it will become harder to find specific information they need. This epic focuses on adding search, filtering, and better navigation to transactions. To enable this, we'll also need a new indexer for SputnikDAO which will provide the backend support to enable this frontend capabilities.

# Acceptance Criteria
- [ ] **Filter/Search:** Users are able to sort & search requests throughout the application (e.g. payments, stake delegation, asset exchange, etc)
- [ ] **Transaction:** Users are able find transaction links for completed requests in history
- [ ] **Speed:** Sort, search, and filter are performant and load fast.
